// <auto-generated />
using System;
using Fiefdom.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiefdom.Migrations
{
    [DbContext(typeof(FiefContext))]
    partial class FiefContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Fiefdom.Context.Fief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("SessionId");

                    b.Property<int>("Title");

                    b.HasKey("Id");

                    b.ToTable("Fiefdom");
                });

            modelBuilder.Entity("Fiefdom.Context.FiefdomPlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FiefId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("FiefId");

                    b.ToTable("FiefdomPlot");
                });

            modelBuilder.Entity("Fiefdom.Context.FiefdomResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FiefId");

                    b.Property<int>("Quantity");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("FiefId");

                    b.ToTable("FiefdomResources");
                });

            modelBuilder.Entity("Fiefdom.Context.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentDay");

                    b.HasKey("Id");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("Fiefdom.Context.Market", b =>
                {
                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<int>("Price");

                    b.HasKey("Type");

                    b.ToTable("Market");
                });

            modelBuilder.Entity("Fiefdom.Context.FiefdomPlot", b =>
                {
                    b.HasOne("Fiefdom.Context.Fief")
                        .WithMany("FiefdomPlot")
                        .HasForeignKey("FiefId");
                });

            modelBuilder.Entity("Fiefdom.Context.FiefdomResources", b =>
                {
                    b.HasOne("Fiefdom.Context.Fief")
                        .WithMany("FiefdomResources")
                        .HasForeignKey("FiefId");
                });
#pragma warning restore 612, 618
        }
    }
}
